<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Password generator</title>
	<style type="text/css">*{margin:0;padding:0;}*,:before,:after{-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box;}body{background-color:#f3f3f3;color:#333;font-family:arial,helvetica,sans-serif;font-size:14px;line-height:1.6em;position:relative;}.container{margin:0 auto;padding:2em;width:960px;}h1,h2,h3,h4{line-height:1.4em;margin:.4em 0 .6em;padding:0;}p{margin-bottom:1.4em;}hr{border:0;border-top:1px solid #ddd;margin:1.4em 0;}input[type="text"],input[type="password"],input[type="email"],input[type="tel"],input[type="search"],select{-o-transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,.075);-webkit-transition:border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;background-color:#fff;background-image:none;border:1px solid #ccc;border-radius:4px;box-shadow:inset 0 1px 1px rgba(0,0,0,.075);color:#555;display:block;height:38px;line-height:1.42857143;padding:8px 12px;transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;width:100%;}.field{margin:1em 0 2em;}.whitebox{-moz-border-radius:.4em;-moz-box-shadow:0 0 .5em #ccc;-webkit-border-radius:.4em;-webkit-box-shadow:0 0 .5em #ccc;background-color:#fff;background-image:none;border:1px solid #ccc;border-radius:.4em;box-shadow:0 0 .4em #ccc;min-height:420px;padding:2em 2em 3em;}.btn{-moz-box-shadow:inset 0 1px 0 0 #c1ed9c;-webkit-box-shadow:inset 0 1px 0 0 #c1ed9c;background:0;background-color:#9dce2c;border:1px solid #83c41a;box-shadow:inset 0 1px 0 0 #c1ed9c;color:#fff;cursor:pointer;display:inline-block;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#9dce2c',endColorstr='#8cb82b');font-family:Arial;font-size:15px;font-style:normal;font-weight:700;height:50px;line-height:50px;padding:0 2em;text-align:center;text-decoration:none;text-indent:0;text-shadow:1px 1px 0 #689324;}.btn:hover{background:0;background-color:#8cb82b;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#8cb82b',endColorstr='#9dce2c');}.btn:active{position:relative;top:1px;}.field_contain .field{width:50%;}.field_contain label{clear:both;display:block;font-size:1.2em;font-weight:700;margin-bottom:.6em;width:100%;}#output_container{margin-top:1em;}#output_container input[type="text"]{clear:both;font-size:1.4em;height:42px;padding:10px 14px;}</style>
</head>
<body>
	<div class="container">
		<div class="whitebox">
			<h1>Password generator</h1>
			<p>
				Click the button below to generate a secure random password from characters A-Z, a-z, 0-9, and _.  Although not the type of password you generally memorize, similar characters were removed, such as 0 and O.
			</p>	
			<hr />
			<form id="form_password_generate" name="form_password_generate" action="#" method="post" role="form">
				<div class="field_contain">
					<div class="field">
						<label>Length of string</label>
						<select name="length" id="input_length">
							<?php for ( $i=8;$i<21;$i++ ): ?>
								<option value="<?php echo $i; ?>"<?php echo $i==15 ? ' selected="selected"' : '';?>><?php echo $i; echo $i==15 ? ' (recommended minimum)' : '';?></option>
							<?php endfor; ?>
						</select>
					</div>
				</div>
				<div class="field">
					<div class="checkbox">
						<label>
							<input id="input_underscores" name="input_underscores" type="checkbox" checked="checked" /> Include underscores (_) - <i><b>Recommended</b></i>
						</label>
					</div>
				</div>
				<div class="field">
					<div class="checkbox">
						<label>
							<input id="input_special" name="input_special" type="checkbox" /> Include special characters (@, #, $, %, etc.) - <i><b>Recommended</b></i>
						</label>
					</div>
				</div>
				<div class="field">
					<a href="#" class="btn generate_trigger">Generate Password</a>
				</div>
				<div id="output_container" class="field_contain">
					<hr />
					<div class="field">
						<label>Your generated password is:</label>
						<input type="text" id="output_target" value="" />
					</div>
				</div>
			</form>
			<hr />
			<p>
				<b>NOTE:</b> your password is generated by JavaScript on the client-side (i.e. in your browser / device).  It is not printed or posted to anywhere except your browser / device screen, so the result is completely private and secure.
			</p>
		</div>
		<script type="text/javascript">
			/* JS function to generate random string - preferred method */
			function random_string(len, use_underscores, use_special)
			{
				var str = '';
				var alphanum_chars = 'abcdefghijkmnprstuvwxyzACDEFGHJKLMNPRTUVWXY2346789'; /* similar chars removed - e.g. 0 and O */
				var special_chars = '!@#$%^*?'; 
				var underscores = '____'; /* multiple to make them more likely */
				var chars = alphanum_chars;
				if (use_underscores)
				{
					chars = chars + underscores;
				}
				if (use_special)
				{
					chars = chars + special_chars;
				}
				str += alphanum_chars.charAt(Math.floor(Math.random() * alphanum_chars.length)); /* first character should be alpha-numeric */
				for( var i=0; i < len - 2; i++ ) 
				{
					str += chars.charAt(Math.floor(Math.random() * chars.length)); /* middle chars can be anything */
				}
				str += alphanum_chars.charAt(Math.floor(Math.random() * alphanum_chars.length)); /* last character should be alpha-numeric */
				return str;
			} 
			
			/* add event listener function */
			var generate_btns = document.getElementsByClassName('generate_trigger');
			
			var print_string = function(e) 
			{
				e.preventDefault();
				var output_target = document.getElementById('output_target');
				var input_length_el = document.getElementById('input_length');
				var input_length_val = input_length_el.options[input_length_el.selectedIndex].value;
				var use_underscores = document.getElementById('input_underscores').checked;
				var use_special = document.getElementById('input_special').checked;
				var result = random_string(input_length_val, use_underscores, use_special);
				output_target.value = result;
			};
			
			for( var i = 0;i < generate_btns.length; i++ )
			{
				generate_btns[i].addEventListener('click', print_string, false);
			}
		</script>
	</div>
</body>
</html>